-- ============================================================================
--  Dolce / Polished by Dolce / Core  —  DATABASE SCHEMA
--  "One Account. Three Brands."
-- ============================================================================
--
--  WHAT THIS FILE IS
--  This is the single source of truth for the shape of the Supabase database.
--  Every table, every column and every security rule the app relies on is
--  defined here. If this file and the live database ever disagree, this file
--  is right and the database should be re-synced by running this file again.
--
--  HOW TO RUN IT
--  Supabase dashboard -> SQL Editor -> New query -> paste this whole file ->
--  Run. It is safe to run more than once: everything is written as
--  "create if it isn't already there", so re-running it never deletes data.
--
--  ORDER: run supabase_schema.sql (this file) first, then
--         supabase_auth_setup.sql, then supabase_seed.sql.
--
--  A NOTE ON MONEY
--  Every price in this database is US dollars. Always. The app's USD/IQD
--  toggle is a display conversion only and nothing is ever stored in dinar.
--  That is why every money column is named "..._usd".
--
--  A NOTE ON IDs
--  IDs are text, not numbers, and they are generated by the app (e.g.
--  'p_m4x9k2a1'). This lets a device that is temporarily offline create a
--  record with an ID that will not collide with one created on another
--  device, and lets the same record keep one identity everywhere.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  0. Housekeeping helpers
-- ----------------------------------------------------------------------------

-- Stamps updated_at automatically on every UPDATE, so we always know when a
-- row last changed without the app having to remember to set it.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;


-- ----------------------------------------------------------------------------
--  0b. PRE-FLIGHT CHECK — is the existing database compatible?
-- ----------------------------------------------------------------------------
--  If this project already has tables from an earlier attempt, this checks
--  that the important columns are the right kind of thing before anything is
--  changed. If something cannot be repaired automatically it stops here with
--  a plain-English list of what is wrong, rather than half-applying the file
--  and leaving the database in a confusing state.
do $$
declare
  problems text := '';
  r record;
begin
  for r in
    select * from (values
      ('profiles','id','uuid'),
      ('profiles','brands','ARRAY'),
      ('services','id','text'),
      ('services','brand','text'),
      ('products','id','text'),
      ('products','brand','text'),
      ('offers','id','text'),
      ('offers','brand','text'),
      ('brand_images','brand','text'),
      ('settings','key','text'),
      ('clients','id','text'),
      ('bookings','id','text'),
      ('bookings','brand','text'),
      ('media','id','text'),
      ('media','brand','text'),
      ('purchases','id','text'),
      ('purchases','brand','text'),
      ('product_sales','id','text'),
      ('product_sales','brand','text'),
      ('register_closes','id','text'),
      ('register_closes','brands','ARRAY')
    ) as v(tbl,col,want)
  loop
    if exists (select 1 from information_schema.tables
               where table_schema='public' and table_name=r.tbl) then
      if exists (select 1 from information_schema.columns c
                 where c.table_schema='public' and c.table_name=r.tbl
                   and c.column_name=r.col
                   and c.data_type <> r.want) then
        problems := problems || format(E'\n  - table "%s", column "%s" is the wrong type (found %s, needs %s)',
          r.tbl, r.col,
          (select c.data_type from information_schema.columns c
            where c.table_schema='public' and c.table_name=r.tbl and c.column_name=r.col),
          r.want);
      end if;
    end if;
  end loop;

  if problems <> '' then
    raise exception E'This project has tables from an earlier attempt that cannot be repaired automatically:%\n\nThese tables hold no real business data yet, so the fix is simply to clear them out and start clean: run supabase_reset.sql, then run this file again. Nothing you have entered in the app is stored there yet, and your staff logins are not affected.', problems;
  end if;
end $$;

-- ----------------------------------------------------------------------------
--  0c. Bring any existing table up to date
-- ----------------------------------------------------------------------------
--  Adds any column that is missing from a table created by an earlier version.
--  Columns are added without a NOT NULL rule, because a table that already has
--  rows in it cannot suddenly require a value it does not have. Fresh tables
--  get the full rules from the CREATE TABLE statements further down.

-- profiles
alter table if exists public.profiles add column if not exists name text;
alter table if exists public.profiles add column if not exists login_slug text;
alter table if exists public.profiles add column if not exists brands text[] default '{}';
alter table if exists public.profiles add column if not exists tabs text[] default '{}';
alter table if exists public.profiles add column if not exists is_owner boolean default false;
alter table if exists public.profiles add column if not exists created_at timestamptz default now();
alter table if exists public.profiles add column if not exists updated_at timestamptz default now();

-- services
alter table if exists public.services add column if not exists brand text;
alter table if exists public.services add column if not exists name text;
alter table if exists public.services add column if not exists category text;
alter table if exists public.services add column if not exists duration text;
alter table if exists public.services add column if not exists price_usd numeric default 0;
alter table if exists public.services add column if not exists discount_percent integer default 0;
alter table if exists public.services add column if not exists description text default '';
alter table if exists public.services add column if not exists points jsonb default '[]'::jsonb;
alter table if exists public.services add column if not exists image text default '';
alter table if exists public.services add column if not exists sort_order integer default 0;
alter table if exists public.services add column if not exists created_at timestamptz default now();
alter table if exists public.services add column if not exists updated_at timestamptz default now();

-- products
alter table if exists public.products add column if not exists brand text;
alter table if exists public.products add column if not exists name text;
alter table if exists public.products add column if not exists price_usd numeric default 0;
alter table if exists public.products add column if not exists discount_percent integer default 0;
alter table if exists public.products add column if not exists stock integer default 0;
alter table if exists public.products add column if not exists image text default '';
alter table if exists public.products add column if not exists created_at timestamptz default now();
alter table if exists public.products add column if not exists updated_at timestamptz default now();

-- offers
alter table if exists public.offers add column if not exists brand text;
alter table if exists public.offers add column if not exists title text;
alter table if exists public.offers add column if not exists subtitle text default '';
alter table if exists public.offers add column if not exists created_at timestamptz default now();
alter table if exists public.offers add column if not exists updated_at timestamptz default now();

-- brand_images
alter table if exists public.brand_images add column if not exists brand text;
alter table if exists public.brand_images add column if not exists image_url text default '';
alter table if exists public.brand_images add column if not exists updated_at timestamptz default now();

-- settings
alter table if exists public.settings add column if not exists value text;
alter table if exists public.settings add column if not exists updated_at timestamptz default now();

-- clients
alter table if exists public.clients add column if not exists phone text;
alter table if exists public.clients add column if not exists name text;
alter table if exists public.clients add column if not exists points integer default 0;
alter table if exists public.clients add column if not exists created_at timestamptz default now();
alter table if exists public.clients add column if not exists updated_at timestamptz default now();

-- bookings
alter table if exists public.bookings add column if not exists brand text;
alter table if exists public.bookings add column if not exists service_id text;
alter table if exists public.bookings add column if not exists service_name text;
alter table if exists public.bookings add column if not exists date_label text;
alter table if exists public.bookings add column if not exists time_label text;
alter table if exists public.bookings add column if not exists date_iso date;
alter table if exists public.bookings add column if not exists status text default 'Requested';
alter table if exists public.bookings add column if not exists client_name text;
alter table if exists public.bookings add column if not exists client_id text;
alter table if exists public.bookings add column if not exists created_at timestamptz default now();
alter table if exists public.bookings add column if not exists updated_at timestamptz default now();

-- media
alter table if exists public.media add column if not exists brand text;
alter table if exists public.media add column if not exists service_id text default '';
alter table if exists public.media add column if not exists type text default 'photo';
alter table if exists public.media add column if not exists kind text default 'before-after';
alter table if exists public.media add column if not exists visibility text default 'private';
alter table if exists public.media add column if not exists consent boolean default false;
alter table if exists public.media add column if not exists client_name text default '';
alter table if exists public.media add column if not exists note text default '';
alter table if exists public.media add column if not exists data_url text;
alter table if exists public.media add column if not exists mime text;
alter table if exists public.media add column if not exists created_at timestamptz default now();
alter table if exists public.media add column if not exists updated_at timestamptz default now();

-- purchases
alter table if exists public.purchases add column if not exists product_id text;
alter table if exists public.purchases add column if not exists name text;
alter table if exists public.purchases add column if not exists brand text;
alter table if exists public.purchases add column if not exists qty integer default 0;
alter table if exists public.purchases add column if not exists unit_cost_usd numeric default 0;
alter table if exists public.purchases add column if not exists total_usd numeric default 0;
alter table if exists public.purchases add column if not exists supplier text default '';
alter table if exists public.purchases add column if not exists date_label text;
alter table if exists public.purchases add column if not exists date_iso date;
alter table if exists public.purchases add column if not exists created_at timestamptz default now();
alter table if exists public.purchases add column if not exists updated_at timestamptz default now();

-- product_sales
alter table if exists public.product_sales add column if not exists product_id text;
alter table if exists public.product_sales add column if not exists name text;
alter table if exists public.product_sales add column if not exists brand text;
alter table if exists public.product_sales add column if not exists qty integer default 0;
alter table if exists public.product_sales add column if not exists unit_price_usd numeric default 0;
alter table if exists public.product_sales add column if not exists total_usd numeric default 0;
alter table if exists public.product_sales add column if not exists client_name text default '';
alter table if exists public.product_sales add column if not exists date_label text;
alter table if exists public.product_sales add column if not exists date_iso date;
alter table if exists public.product_sales add column if not exists created_at timestamptz default now();
alter table if exists public.product_sales add column if not exists updated_at timestamptz default now();

-- register_closes
alter table if exists public.register_closes add column if not exists date_label text;
alter table if exists public.register_closes add column if not exists date_iso date;
alter table if exists public.register_closes add column if not exists brands text[] default '{}';
alter table if exists public.register_closes add column if not exists expected_total_usd numeric default 0;
alter table if exists public.register_closes add column if not exists counted_cash_usd numeric default 0;
alter table if exists public.register_closes add column if not exists counted_card_usd numeric default 0;
alter table if exists public.register_closes add column if not exists counted_total_usd numeric default 0;
alter table if exists public.register_closes add column if not exists notes text default '';
alter table if exists public.register_closes add column if not exists closed_by text;
alter table if exists public.register_closes add column if not exists closed_at text;
alter table if exists public.register_closes add column if not exists created_at timestamptz default now();
alter table if exists public.register_closes add column if not exists updated_at timestamptz default now();

-- ----------------------------------------------------------------------------
--  0d. Stop leftover columns from blocking new records
-- ----------------------------------------------------------------------------
--  An older version of a table may have a column this app no longer uses (for
--  example a single "brand" where the register now records a list of them). If
--  such a column insists on always having a value, every new record would be
--  rejected. This relaxes that rule on leftovers only — the columns this app
--  actually uses are untouched, and no data is deleted.
do $$
declare r record; keep text[];
begin
  for r in
    select * from (values
      ('profiles', array['id','name','login_slug','brands','tabs','is_owner','created_at','updated_at']),
      ('services', array['id','brand','name','category','duration','price_usd','discount_percent','description','points','image','sort_order','created_at','updated_at']),
      ('products', array['id','brand','name','price_usd','discount_percent','stock','image','created_at','updated_at']),
      ('offers', array['id','brand','title','subtitle','created_at','updated_at']),
      ('brand_images', array['brand','image_url','updated_at']),
      ('settings', array['key','value','updated_at']),
      ('clients', array['id','phone','name','points','created_at','updated_at']),
      ('bookings', array['id','brand','service_id','service_name','date_label','time_label','date_iso','status','client_name','client_id','created_at','updated_at']),
      ('media', array['id','brand','service_id','type','kind','visibility','consent','client_name','note','data_url','mime','created_at','updated_at']),
      ('purchases', array['id','product_id','name','brand','qty','unit_cost_usd','total_usd','supplier','date_label','date_iso','created_at','updated_at']),
      ('product_sales', array['id','product_id','name','brand','qty','unit_price_usd','total_usd','client_name','date_label','date_iso','created_at','updated_at']),
      ('register_closes', array['id','date_label','date_iso','brands','expected_total_usd','counted_cash_usd','counted_card_usd','counted_total_usd','notes','closed_by','closed_at','created_at','updated_at'])
    ) as v(tbl, cols)
  loop
    keep := r.cols;
    execute (
      select coalesce(string_agg(format('alter table public.%I alter column %I drop not null;', r.tbl, c.column_name), ' '), 'select 1')
      from information_schema.columns c
      where c.table_schema='public' and c.table_name=r.tbl
        and c.is_nullable='NO' and c.column_default is null
        and not (c.column_name = any(keep))
    );
  end loop;
end $$;


-- ----------------------------------------------------------------------------
--  1. profiles — the staff/employee accounts
-- ----------------------------------------------------------------------------
--  Each row belongs one-to-one with a hidden Supabase Auth user. Staff still
--  just pick their name and type a 4-digit PIN in the app; the PIN is the
--  password on that hidden account and is checked by Supabase, never stored
--  here in plain text.
--
--  brands  = which departments this person can see  (dolce / polished / core)
--  tabs    = which admin sections this person can open
--  is_owner= full access, can manage other employees

create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  name        text not null,
  login_slug  text unique,
  brands      text[] not null default '{}',
  tabs        text[] not null default '{}',
  is_owner    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);


create index if not exists profiles_login_slug_idx on public.profiles (login_slug);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();


-- ----------------------------------------------------------------------------
--  2. Permission helpers
-- ----------------------------------------------------------------------------
--  These read the logged-in staff member's own profile row and are used by
--  every security rule below. They are SECURITY DEFINER, which means they can
--  read the profiles table directly without tripping over the profiles table's
--  own security rules (that would be circular). The empty search_path is a
--  standard hardening step so the function can't be tricked into calling
--  something else with the same name.

create or replace function public.my_brands()
returns text[]
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select p.brands from public.profiles p where p.id = auth.uid()), '{}'::text[]);
$$;

create or replace function public.my_tabs()
returns text[]
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select p.tabs from public.profiles p where p.id = auth.uid()), '{}'::text[]);
$$;

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce((select p.is_owner from public.profiles p where p.id = auth.uid()), false);
$$;

-- Is this person allowed into this admin section?
create or replace function public.has_tab(t text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_owner() or (t = any(public.my_tabs()));
$$;

-- Is this person allowed to touch this department's data?
create or replace function public.can_brand(b text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_owner() or (b = any(public.my_brands()));
$$;

-- Same question for a record that covers several departments at once
-- (an end-of-day register close can cover more than one).
create or replace function public.can_brands(bs text[])
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select public.is_owner() or (bs <@ public.my_brands());
$$;

-- Can this person write to the admin section named `t`, for department `b`?
create or replace function public.can_write(t text, b text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select auth.uid() is not null and public.has_tab(t) and public.can_brand(b);
$$;


-- ----------------------------------------------------------------------------
--  3. The public catalog — services, products, offers, brand photos, settings
-- ----------------------------------------------------------------------------
--  Anyone can READ these, including a visitor who has not logged in — that is
--  the whole point, it is the shop window. Only staff can change them.

create table if not exists public.services (
  id               text primary key,
  brand            text not null,
  name             text not null,
  category         text,
  duration         text,
  price_usd        numeric(10,2) not null default 0,
  discount_percent integer not null default 0,
  description      text default '',
  points           jsonb not null default '[]'::jsonb,
  image            text default '',
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists services_brand_idx on public.services (brand);

create table if not exists public.products (
  id               text primary key,
  brand            text not null,
  name             text not null,
  price_usd        numeric(10,2) not null default 0,
  discount_percent integer not null default 0,
  stock            integer not null default 0,
  image            text default '',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index if not exists products_brand_idx on public.products (brand);

create table if not exists public.offers (
  id         text primary key,
  brand      text not null,
  title      text not null,
  subtitle   text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists offers_brand_idx on public.offers (brand);

-- One hero photo per brand, shown on the welcome screen.
create table if not exists public.brand_images (
  brand      text primary key,
  image_url  text default '',
  updated_at timestamptz not null default now()
);

-- Small key/value table. Today it holds one thing: the USD -> IQD display
-- rate, which the owner edits from the Overview tab because the market rate
-- moves. Room to grow without another migration.
create table if not exists public.settings (
  key        text primary key,
  value      text,
  updated_at timestamptz not null default now()
);


-- ----------------------------------------------------------------------------
--  4. Clients — customer accounts (one per phone number, all three brands)
-- ----------------------------------------------------------------------------
create table if not exists public.clients (
  id         text primary key,
  phone      text not null unique,
  name       text not null,
  points     integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- ----------------------------------------------------------------------------
--  5. Bookings
-- ----------------------------------------------------------------------------
--  date_label / time_label are the human strings the app shows and matches on
--  ("Aug 29, 2026", "11:00 AM"). date_iso is the same day as a real date, kept
--  alongside it so the database can sort, filter and report by date properly.
create table if not exists public.bookings (
  id           text primary key,
  brand        text not null,
  service_id   text,
  service_name text,
  date_label   text,
  time_label   text,
  date_iso     date,
  status       text not null default 'Requested'
,
  client_name  text,
  client_id    text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists bookings_brand_idx on public.bookings (brand);
create index if not exists bookings_date_iso_idx on public.bookings (date_iso);
create index if not exists bookings_status_idx on public.bookings (status);


-- ----------------------------------------------------------------------------
--  6. Photos & video
-- ----------------------------------------------------------------------------
--  data_url holds the image itself. See the note at the bottom of this file
--  about moving these to Supabase Storage as the gallery grows.
create table if not exists public.media (
  id          text primary key,
  brand       text not null,
  service_id  text default '',
  type        text not null default 'photo',
  kind        text not null default 'before-after',
  visibility  text not null default 'private',
  consent     boolean not null default false,
  client_name text default '',
  note        text default '',
  data_url    text,
  mime        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index if not exists media_brand_idx on public.media (brand);
create index if not exists media_visibility_idx on public.media (visibility);

-- (The consent rule, and every other rule this table follows, is applied in
-- section 7b below so that older tables get it too.)


-- ----------------------------------------------------------------------------
--  7. Inventory & money movements
-- ----------------------------------------------------------------------------

-- Stock coming IN (a delivery from a supplier).
create table if not exists public.purchases (
  id            text primary key,
  product_id    text,
  name          text,
  brand         text not null,
  qty           integer not null default 0,
  unit_cost_usd numeric(10,2) not null default 0,
  total_usd     numeric(12,2) not null default 0,
  supplier      text default '',
  date_label    text,
  date_iso      date,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index if not exists purchases_brand_idx on public.purchases (brand);
create index if not exists purchases_date_iso_idx on public.purchases (date_iso);

-- Stock going OUT (a retail sale at the counter).
create table if not exists public.product_sales (
  id             text primary key,
  product_id     text,
  name           text,
  brand          text not null,
  qty            integer not null default 0,
  unit_price_usd numeric(10,2) not null default 0,
  total_usd      numeric(12,2) not null default 0,
  client_name    text default '',
  date_label     text,
  date_iso       date,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create index if not exists product_sales_brand_idx on public.product_sales (brand);
create index if not exists product_sales_date_iso_idx on public.product_sales (date_iso);

-- End-of-day cash-up. One row can cover more than one department, which is why
-- `brands` is a list rather than a single value.
create table if not exists public.register_closes (
  id                 text primary key,
  date_label         text,
  date_iso           date,
  brands             text[] not null default '{}',
  expected_total_usd numeric(12,2) not null default 0,
  counted_cash_usd   numeric(12,2) not null default 0,
  counted_card_usd   numeric(12,2) not null default 0,
  counted_total_usd  numeric(12,2) not null default 0,
  notes              text default '',
  closed_by          text,
  closed_at          text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists register_closes_date_iso_idx on public.register_closes (date_iso);


-- ----------------------------------------------------------------------------
--  7b. The rules the database enforces on its own
-- ----------------------------------------------------------------------------
--  These are the sanity checks that hold no matter which app, device or person
--  is writing: a brand has to be one of the three real ones, a price cannot be
--  negative, a discount cannot be more than 99%, stock cannot go below zero, a
--  booking has to have a real status, and a gallery photo cannot be marked
--  public unless consent was ticked.
--
--  They are written here rather than inside the table definitions above so
--  that they also get applied to tables left over from an earlier attempt,
--  which would otherwise quietly have no rules at all.
--
--  Each is added as "not valid", which means: enforce this on everything from
--  now on, but do not reject the file because of an odd row already sitting in
--  an old table. New and edited records are fully checked either way.

do $$
declare r record;
begin
  for r in
    select * from (values
      ('services','services_brand_ck',        $q$brand in ('dolce','polished','core')$q$),
      ('services','services_price_ck',        $q$price_usd >= 0$q$),
      ('services','services_discount_ck',     $q$discount_percent between 0 and 99$q$),
      ('products','products_brand_ck',        $q$brand in ('dolce','polished','core')$q$),
      ('products','products_price_ck',        $q$price_usd >= 0$q$),
      ('products','products_discount_ck',     $q$discount_percent between 0 and 99$q$),
      ('products','products_stock_ck',        $q$stock >= 0$q$),
      ('offers','offers_brand_ck',            $q$brand in ('dolce','polished','core')$q$),
      ('brand_images','brand_images_brand_ck',$q$brand in ('dolce','polished','core')$q$),
      ('bookings','bookings_brand_ck',        $q$brand in ('dolce','polished','core')$q$),
      ('bookings','bookings_status_ck',       $q$status in ('Requested','Confirmed','Completed','Cancelled')$q$),
      ('media','media_brand_ck',              $q$brand in ('dolce','polished','core')$q$),
      ('media','media_type_ck',               $q$type in ('photo','video')$q$),
      ('media','media_kind_ck',               $q$kind in ('before-after','process')$q$),
      ('media','media_visibility_ck',         $q$visibility in ('public','private')$q$),
      ('media','media_public_needs_consent',  $q$visibility <> 'public' or consent = true$q$),
      ('purchases','purchases_brand_ck',      $q$brand in ('dolce','polished','core')$q$),
      ('purchases','purchases_qty_ck',        $q$qty > 0$q$),
      ('purchases','purchases_cost_ck',       $q$unit_cost_usd >= 0$q$),
      ('product_sales','product_sales_brand_ck',$q$brand in ('dolce','polished','core')$q$),
      ('product_sales','product_sales_qty_ck',  $q$qty > 0$q$),
      ('product_sales','product_sales_price_ck',$q$unit_price_usd >= 0$q$),
      ('clients','clients_points_ck',         $q$points >= 0$q$)
    ) as v(tbl,cname,rule)
  loop
    if exists (select 1 from information_schema.tables
               where table_schema='public' and table_name=r.tbl) then
      execute format('alter table public.%I drop constraint if exists %I', r.tbl, r.cname);
      execute format('alter table public.%I add constraint %I check (%s) not valid', r.tbl, r.cname, r.rule);
    end if;
  end loop;
end $$;

-- One customer account per phone number, however the row got there.
create unique index if not exists clients_phone_key on public.clients (phone);

-- ----------------------------------------------------------------------------
--  8. updated_at triggers for every table above
-- ----------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'services','products','offers','brand_images','settings','clients',
    'bookings','media','purchases','product_sales','register_closes'
  ] loop
    execute format('drop trigger if exists %I on public.%I', t || '_set_updated_at', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
      t || '_set_updated_at', t);
  end loop;
end $$;


-- ============================================================================
--  9. ROW LEVEL SECURITY
-- ============================================================================
--  Row Level Security means the database itself decides who may see or change
--  each row. It is enforced no matter how someone connects, so a person who
--  got hold of the app's public key still cannot read another department's
--  numbers or edit prices.
--
--  The public key that ships inside the app is deliberately powerless on its
--  own: without logging in it can read the shop window and nothing else.
-- ============================================================================

alter table public.profiles        enable row level security;
alter table public.services        enable row level security;
alter table public.products        enable row level security;
alter table public.offers          enable row level security;
alter table public.brand_images    enable row level security;
alter table public.settings        enable row level security;
alter table public.clients         enable row level security;
alter table public.bookings        enable row level security;
alter table public.media           enable row level security;
alter table public.purchases       enable row level security;
alter table public.product_sales   enable row level security;
alter table public.register_closes enable row level security;

-- ---- profiles --------------------------------------------------------------
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_owner());

drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated
  with check (public.is_owner() or id = auth.uid());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated
  using (id = auth.uid() or public.is_owner())
  with check (id = auth.uid() or public.is_owner());

drop policy if exists profiles_delete on public.profiles;
create policy profiles_delete on public.profiles for delete to authenticated
  using (public.is_owner() and id <> auth.uid());   -- an owner cannot delete themselves

-- ---- services --------------------------------------------------------------
drop policy if exists services_read on public.services;
create policy services_read on public.services for select to anon, authenticated using (true);

drop policy if exists services_insert on public.services;
create policy services_insert on public.services for insert to authenticated
  with check (public.can_write('services', brand));

drop policy if exists services_update on public.services;
create policy services_update on public.services for update to authenticated
  using (public.can_write('services', brand)) with check (public.can_write('services', brand));

drop policy if exists services_delete on public.services;
create policy services_delete on public.services for delete to authenticated
  using (public.can_write('services', brand));

-- ---- products --------------------------------------------------------------
drop policy if exists products_read on public.products;
create policy products_read on public.products for select to anon, authenticated using (true);

drop policy if exists products_insert on public.products;
create policy products_insert on public.products for insert to authenticated
  with check (public.can_write('products', brand));

drop policy if exists products_update on public.products;
create policy products_update on public.products for update to authenticated
  using (public.can_write('products', brand)) with check (public.can_write('products', brand));

drop policy if exists products_delete on public.products;
create policy products_delete on public.products for delete to authenticated
  using (public.can_write('products', brand));

-- ---- offers ----------------------------------------------------------------
drop policy if exists offers_read on public.offers;
create policy offers_read on public.offers for select to anon, authenticated using (true);

drop policy if exists offers_insert on public.offers;
create policy offers_insert on public.offers for insert to authenticated
  with check (public.can_write('offers', brand));

drop policy if exists offers_update on public.offers;
create policy offers_update on public.offers for update to authenticated
  using (public.can_write('offers', brand)) with check (public.can_write('offers', brand));

drop policy if exists offers_delete on public.offers;
create policy offers_delete on public.offers for delete to authenticated
  using (public.can_write('offers', brand));

-- ---- brand_images ----------------------------------------------------------
drop policy if exists brand_images_read on public.brand_images;
create policy brand_images_read on public.brand_images for select to anon, authenticated using (true);

drop policy if exists brand_images_write on public.brand_images;
create policy brand_images_write on public.brand_images for all to authenticated
  using (public.can_write('overview', brand)) with check (public.can_write('overview', brand));

-- ---- settings (exchange rate) ---------------------------------------------
drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select to anon, authenticated using (true);

drop policy if exists settings_write on public.settings;
create policy settings_write on public.settings for all to authenticated
  using (public.is_owner()) with check (public.is_owner());

-- ---- clients ---------------------------------------------------------------
--  A visitor signing up on the client app is not a logged-in staff member, so
--  anon is allowed to create an account row. It is NOT allowed to read the
--  customer list back, so nobody can pull your client database out of the app.
drop policy if exists clients_signup on public.clients;
create policy clients_signup on public.clients for insert to anon, authenticated with check (true);

drop policy if exists clients_staff_read on public.clients;
create policy clients_staff_read on public.clients for select to authenticated
  using (auth.uid() is not null);

drop policy if exists clients_staff_write on public.clients;
create policy clients_staff_write on public.clients for update to authenticated
  using (auth.uid() is not null) with check (auth.uid() is not null);

drop policy if exists clients_staff_delete on public.clients;
create policy clients_staff_delete on public.clients for delete to authenticated
  using (public.is_owner());

-- ---- bookings --------------------------------------------------------------
--  Same idea: a customer can REQUEST a booking without logging in (it is a
--  request form), but only staff can see the diary or change a booking's
--  status. The WITH CHECK pins anon inserts to status 'Requested' so nobody
--  can slip a pre-confirmed booking into the diary.
drop policy if exists bookings_request on public.bookings;
create policy bookings_request on public.bookings for insert to anon
  with check (status = 'Requested');

drop policy if exists bookings_staff_insert on public.bookings;
create policy bookings_staff_insert on public.bookings for insert to authenticated
  with check (public.can_write('bookings', brand));

drop policy if exists bookings_staff_read on public.bookings;
create policy bookings_staff_read on public.bookings for select to authenticated
  using (public.has_tab('bookings') and public.can_brand(brand));

drop policy if exists bookings_staff_update on public.bookings;
create policy bookings_staff_update on public.bookings for update to authenticated
  using (public.can_write('bookings', brand)) with check (public.can_write('bookings', brand));

drop policy if exists bookings_staff_delete on public.bookings;
create policy bookings_staff_delete on public.bookings for delete to authenticated
  using (public.can_write('bookings', brand));

-- ---- media -----------------------------------------------------------------
--  Public gallery items are readable by anyone (they are on the service pages).
--  Private client records are staff-only, and only the departments that person
--  works in.
drop policy if exists media_public_read on public.media;
create policy media_public_read on public.media for select to anon, authenticated
  using (visibility = 'public');

drop policy if exists media_staff_read on public.media;
create policy media_staff_read on public.media for select to authenticated
  using (public.has_tab('gallery') and public.can_brand(brand));

drop policy if exists media_staff_write on public.media;
create policy media_staff_write on public.media for all to authenticated
  using (public.can_write('gallery', brand)) with check (public.can_write('gallery', brand));

-- ---- purchases -------------------------------------------------------------
drop policy if exists purchases_staff on public.purchases;
create policy purchases_staff on public.purchases for all to authenticated
  using (public.can_write('purchases', brand)) with check (public.can_write('purchases', brand));

-- ---- product_sales ---------------------------------------------------------
--  Recorded from the Products tab ("Sell"), so it follows the products
--  permission; anyone who can run the Reports tab can read them too.
drop policy if exists product_sales_read on public.product_sales;
create policy product_sales_read on public.product_sales for select to authenticated
  using ((public.has_tab('products') or public.has_tab('reports')) and public.can_brand(brand));

drop policy if exists product_sales_write on public.product_sales;
create policy product_sales_write on public.product_sales for insert to authenticated
  with check (public.can_write('products', brand));

drop policy if exists product_sales_update on public.product_sales;
create policy product_sales_update on public.product_sales for update to authenticated
  using (public.can_write('products', brand)) with check (public.can_write('products', brand));

drop policy if exists product_sales_delete on public.product_sales;
create policy product_sales_delete on public.product_sales for delete to authenticated
  using (public.can_write('products', brand));

-- ---- register_closes -------------------------------------------------------
drop policy if exists register_closes_staff on public.register_closes;
create policy register_closes_staff on public.register_closes for all to authenticated
  using (public.has_tab('reports') and public.can_brands(brands))
  with check (public.has_tab('reports') and public.can_brands(brands));


-- ----------------------------------------------------------------------------
--  9b. Table-level grants
-- ----------------------------------------------------------------------------
--  Row Level Security decides WHICH ROWS someone may touch. These grants
--  decide whether they may touch the table at all. Both have to allow it, so
--  this is a second, coarser lock on the same door — and it means the rules
--  above hold even if the project's default permissions are ever changed.

grant usage on schema public to anon, authenticated;

-- The shop window: readable by anyone, including a visitor who never logs in.
grant select on public.services, public.products, public.offers,
                public.brand_images, public.settings, public.media
  to anon, authenticated;

-- A visitor may ask for a booking and create their own customer account.
-- Nothing more: no reading the diary, no reading the customer list.
grant insert on public.bookings, public.clients to anon;

-- Logged-in staff may work with everything; the rules above then narrow it
-- down to their own departments and their own sections.
grant select, insert, update, delete on
  public.profiles, public.services, public.products, public.offers,
  public.brand_images, public.settings, public.clients, public.bookings,
  public.media, public.purchases, public.product_sales, public.register_closes
  to authenticated;


-- ============================================================================
--  10. Notes for later — deliberately NOT done yet
-- ============================================================================
--  * PHOTOS: images are stored here as text (a base64 "data URL"), which is
--    simple and works, but every photo makes the catalog download bigger for
--    every customer. The proper home for them is Supabase Storage, with only
--    a short link kept in these tables. Worth doing before the gallery grows
--    past a few dozen items.
--
--  * CLIENT LOGIN: customers "log in" with a phone number and a demo code that
--    is not actually texted to them, and that account is not a real Supabase
--    account. That is why the rules above let an anonymous visitor create a
--    booking request but never read the diary back. Real phone login (Supabase
--    Auth SMS) would let a customer see their own bookings from any device.
--
--  * PIN RESET: an owner cannot yet reset another employee's PIN, because
--    doing so needs the secret service key, which must never be put inside the
--    app. That belongs in a small Supabase Edge Function.
--
--  * LIVE UPDATES: devices refresh when the app is opened or refocused. If you
--    later want changes to appear instantly on a second screen without a
--    refresh, enable Supabase Realtime on these tables.
-- ============================================================================
